### PR TITLE
Remove spinners on Socorro in case of errors

### LINKED ISSUE #40: Remove spinners on crash-stats when no data

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #40.

As an example: https://crash-stats.mozilla.com/report/index/abccf2c8-2e3d-499a-bea1-431a40180509#tab-details
The spinner is spinning for ever at line 11 (widget/android/nsWindow.cpp:1817).

### CODE REVIEW

File: socorro.js [hunk 1]
```diff
@@ -60,6 +66,7 @@ if (Object.keys(fileinfo).length != 0) {
       fetchCoverage(revision, filename).then(data => {
         if (data !== null && !data.hasOwnProperty("error")) {
           if (!data.hasOwnProperty("data")) {
+            removeSpinners(lineElements);
```
Comment (marco-c) [inline socorro.js]: Instead of calling removeSpinners here and in the successful case, you could use `finally` on the promise returned by fetchCoverage.then:
```
fetchCoverage(revision, filename)
.then(data => {
    ...
})
.finally(() => {
  // REMOVE SPINNERS HERE
});
```

This way we make sure we will always remove spinners at the end, even if we add another possible failure case in the fetchCoverage function.

Comment (calixteman) [reply socorro.js]: good to know, thx

**Review by marco-c — APPROVED** [review]
